### ISSUE TITLE
Too agressive measurement  frequency requirement

### ISSUE THREAD

**Issue by zidz** [terjesannum/tibber-exporter#10]
I want to start with thanking you for writing this software! It's really amazing.
But the data points is (for me at least) not always fetched with less than a minute in between. Had to fork this and increase from 1 to 2 minutes so the application does not die.
https://github.com/terjesannum/tibber-exporter/blob/8ac7b3b01628a40b5ea4d68ad39e825e0f084455/main.go#L156C12-L156C12

**Comment by terjesannum** [comment]
Strange, I've been running with this interval for over a year without any problems. Do the logs say anything about why the application dies? Tibber documentation says there is a rate limit on 100 request per 5 minutes, but this exporter should be far below that (3 requests per minute). 
Do you have other applications using the Tibber API running at the same time?

**Comment by terjesannum** [comment]
Sorry, I see from your fork that the problem you are experiencing is that there have been no messages in the live feed for a minute. I'm not sure what to expect from different electricity meters, but more than a minute between updates seems very slow. Could the problem be a poor wifi connection for your Pulse?

Anyway, I'll make that timeout configurable with a command line argument...

**Comment by zidz** [comment]
Thanks 👍
