### ISSUE TITLE
No subscription found for home

### ISSUE THREAD

**Issue by ISirRockI** [terjesannum/tibber-exporter#15]
Hello everyone, 
I have just tried to implement the Tibber API project. Unfortunately, grafana does not display any data. It seems that it is because Docker is not receiving any information?
Here is an overview:
![testxx](https://github.com/terjesannum/tibber-exporter/assets/157051673/c91e2cc8-2613-4a87-8d76-7df379db52c5)

I actually stuck strictly to the instructions. How could the problem be solved?

Thanks in advance!

**Comment by terjesannum** [comment]
There is a check for subscription on startup, do you have an active Tibber subscription? The live feed from Tibber Pulse has been reported to work without an active subscription (see Issue #4), but then you have to start the exporter with the `--disable-subscription-check` argument.

**Comment by ISirRockI** [comment]
It worked, thank you!
