### ISSUE TITLE
Monitoring is not started

### ISSUE THREAD

**Issue by SirColeslaw** [terjesannum/tibber-exporter#4]
Hello, yesterday I tried to set up a monitoring for my Grafana dashboard, using your container, but now I have the problem that after starting the tibber-exporter I either get this message here:

`2023/08/17 13:48:22 Starting tibber-exporter/3.1.1 (https://github.com/terjesannum/tibber-exporter)
2023/08/17 13:48:23 Websocket url: wss://[websocket-api.tibber.com/v1-beta/gql/subscriptions](http://websocket-api.tibber.com/v1-beta/gql/subscriptions)
2023/08/17 13:48:23 Found home: xxxxxxx-xxxxxxx-xxxx-xxx-xxxxx-xxxxxxx - Im Steinig 8
2023/08/17 13:48:23 No subscription found for home xxxxxxx-xxxxxxx-xxxx-xxx-xxxxx-xxxxxxx
2023/08/17 13:48:23 Starting http listener`

And after that, no data comes in on the dashboard. 

Or this message here when I set the parameter --live "home id":

`2023/08/18 14:44:27 Starting tibber-exporter/3.1.1 (https://github.com/terjesannum/tibber-exporter)
2023/08/18 14:44:28 Websocket url: wss://websocket-api.tibber.com/v1-beta/gql/subscriptions
2023/08/18 14:44:28 Found home: xxxxxxx-xxxxxxx-xxxx-xxx-xxxxx-xxxxxxx - Im Steinig 8
2023/08/18 14:44:28 No subscription found for home xxxxxxx-xxxxxxx-xxxx-xxx-xxxxx-xxxxxxx
2023/08/18 14:44:28 Monitoring of home xxxxxxx-xxxxxxx-xxxx-xxx-xxxxx-xxxxxxx not started. Exiting...`

And also no data is output in the dashboard.

What am I doing wrong?

**Comment by terjesannum** [comment]
It seems that Tibber doesn't report an active subscription on your home. Do you use the Tibber app and do that work as expected?

Can you try this query in the [Tibber API explorer](https://developer.tibber.com/explorer) (with the same access token):
```
{
  viewer {
    homes {
      id
      appNickname
      currentSubscription {
        id
        validFrom
        validTo
      }
      subscriptions {
        id
        validFrom
        validTo
      }
    }
  }
}
```

**Comment by SirColeslaw** [comment]
I use the Tibber app, which also gives me all the information of my Tiber Pulse, but I don't have an electricity contract with Tibber.

Here is the output of your query:

```
{
  "data": {
    "viewer": {
      "homes": [
        {
          "id": "XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX",
          "appNickname": "Im Steinig 8",
          "currentSubscription": null,
          "subscriptions": []
        }
      ]
    }
  }
}
```

In the meantime, I have tried Home Assistant, which displays the data from the Tibber Pulse.

**Comment by terjesannum** [comment]
Thanks. The exporter is working as intended here, but I assumed that an active subscription was necessary to use the Tibber API services. I'm a bit surprised that this is not needed, but I'll try to make an updated version of the exporter that omits this check. 😄 

One problem I see is that the price information is found under the subscription data that are empty for your home. Are you able to view prices in Home Assistant?

Could you also try to start the Tibber feed in the API explorer so I can see if the cost data is there?

```
subscription {
  liveMeasurement(homeId:"XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX") {
    timestamp
    power
    accumulatedConsumption
    accumulatedCost
  }
}
```

**Comment by SirColeslaw** [comment]
Here is the output:

```
{
  "liveMeasurement": {
    "timestamp": "2023-08-20T11:54:52.000+02:00",
    "power": 3014.83,
    "accumulatedConsumption": 7.3375,
    "accumulatedCost": null
  }
}
```

**Comment by terjesannum** [comment]
Ok, it looks that the data from the Tibber Pulse is available but prices and costs are missing as these are connected to a subscription. I'll try to make an updated version of the exporter later today that handles this.

**Comment by terjesannum** [comment]
I had to add an extra flag for this situation as skipping the subscription check by default can have some unwanted effects.
Try running the latest version (3.2.0) with the `--disable-subscription-check` flag, I hope that will work on a home with Tibber Pulse but without a Tibber subscription

**Comment by SirColeslaw** [comment]
It works! Thank you! Only thing that isnt displayed is the L1 L2 and L3 values, but i think that could be a problem of my smart meter, that it doesnt provide these data for reading.

**Comment by terjesannum** [comment]
Great! I know there are differences in the power meters and how often they report that data. You could try to query Tibber directly, if you see data in the API explorer you should also have them in Prometheus.

```
subscription {
  liveMeasurement(homeId:"XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX") {
    timestamp
    voltagePhase1
    voltagePhase2
    voltagePhase3
    currentL1
    currentL2
    currentL3
  }
}
```

You can also see in the logs from the exporter what is received. I receive updates every 2.5 seconds, but voltage/current only comes every 10 seconds.

**Comment by SirColeslaw** [comment]
Here is the output, but I believe that my smart meter does not transmit this data to the Pulse.

```
{
  "liveMeasurement": {
    "timestamp": "2023-08-20T21:11:10.000+02:00",
    "voltagePhase1": null,
    "voltagePhase2": null,
    "voltagePhase3": null,
    "currentL1": null,
    "currentL2": null,
    "currentL3": null
  }
}
```

**Comment by terjesannum** [comment]
Yes, looks like that. But you did have that open for a while? Mine also looks like that, but every 10 seconds there is a message with data for voltage/current.

**Comment by tmikaeld** [comment]
@terjesannum 
Sorry, I'm a bit noob when it comes to docker, how do i apply the --disable-subscription-check when using docker compose?

**Comment by terjesannum** [comment]
You can do this with adding `command` to the tibber-exporter service in the `docker-compose.yml` file:
```yaml
  tibber-exporter:
    image: ghcr.io/terjesannum/tibber-exporter:latest
    command: ["--disable-subscription-check"]
    ports:
      - "8080:8080"
```

**Comment by tmikaeld** [comment]
@terjesannum This works excellently and I see that you store the data in a sqlite db, is it local to the docker setup? Would it be possible to mount it to a folder instead so it can be backed up?

**Comment by terjesannum** [comment]
There are two data volumes created in the docker compose setup, one for Grafana and one for Prometheus. If you want these on a specific location, change the volume mount for the services:
```yaml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
```

to:
```yaml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /my-dir/my-prometheus-data:/prometheus
```

..and simular for Grafana

**Comment by tmikaeld** [comment]
@terjesannum Thanks! Relative paths worked too 👍
