### ISSUE TITLE
Documentation Request: Data volume

### ISSUE THREAD

**Issue by DaCHack** [terjesannum/tibber-exporter#6]
Hi,

great tool! Thanks for sharing!
Could you please give a quick and rough estimation of the data volumes that need to be stored in order for people to right-size their storage ie SD Card for the raspberry pi?

thanks!

**Comment by terjesannum** [comment]
Prometheus documentation says this:

> Prometheus stores an average of only 1-2 bytes per sample. Thus, to plan the capacity of a Prometheus server, you can use the rough formula:
> 
> needed_disk_space = retention_time_seconds * ingested_samples_per_second * bytes_per_sample

So the storage needed will depend very much on what you use as retention time and scrape frequency. You can also configure Prometheus to use size based retention if you need to limit the storage used.

The exporter returns about 80 metrics, and that with a 1 minute scrape interval and 2 bytes per sample should give 84Mb per year of data.
